apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ipl-2024
  template:
    metadata:
      labels:
        app: ipl-2024
    spec:
      containers:
        - name: ipl
          image: daviddocker526/ipl:latest
          ports:
            - containerPort: 80
